# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip"
    # Enable version updates for development dependencies
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 0 1 */3 *" # Run once every 3 months
    cooldown:
      default-days: 7
    versioning-strategy: "increase-if-necessary"
    groups:
      dev-deps:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    # Enable version updates for GitHub Actions
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 0 1 */3 *" # Run once every 3 months
    cooldown:
      default-days: 7
    groups:
      github-actions:
        patterns:
          - "*"
