TESTS += test_basic.c
TESTS += test_bit_fields.c

SRC += files/c_source/motohawk.c
SRC += files/c_source/padding_bit_order.c
SRC += files/c_source/vehicle.c
SRC += files/c_source/multiplex.c
SRC += files/c_source/multiplex_2.c
SRC += files/c_source/floating_point.c
SRC += files/c_source/no_signals.c
SRC += files/c_source/choices.c
SRC += files/c_source/signed.c
SRC += files/c_source/my_database_name.c
SRC += files/c_source/min_max_only_6_0.c
SRC += files/c_source/abs.c
SRC += files/c_source/motohawk_bit_fields.c
SRC += files/c_source/floating_point_bit_fields.c
SRC += files/c_source/signed_bit_fields.c

CFLAGS += -fpack-struct

include test.mk
