TESTS += test_basic.c
TESTS += test_bit_fields.c

SRC += files/c_source/motohawk_utils.c
SRC += files/c_source/padding_bit_order_utils.c
SRC += files/c_source/vehicle_utils.c
SRC += files/c_source/multiplex_utils.c
SRC += files/c_source/multiplex_2_utils.c
SRC += files/c_source/floating_point_utils.c
SRC += files/c_source/no_signals_utils.c
SRC += files/c_source/choices_utils.c
SRC += files/c_source/signed_utils.c
SRC += files/c_source/my_database_name_utils.c
SRC += files/c_source/min_max_only_6_0_utils.c
SRC += files/c_source/abs_utils.c
SRC += files/c_source/motohawk_bit_fields_utils.c
SRC += files/c_source/floating_point_bit_fields_utils.c
SRC += files/c_source/signed_bit_fields_utils.c

CFLAGS += -fpack-struct

include test.mk
