/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 32.6.1 Thu Jan 24 16:45:28 2019.
 */

#include <string.h>

#include "enums.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

int enums_vehicle_status_pack(
    uint8_t *dst_p,
    const struct enums_vehicle_status_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->inverter_state, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->wheel_speed_sensor_state, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->signed_int_char, 0u, 0xffu);

    return (8);
}

int enums_vehicle_status_unpack(
    struct enums_vehicle_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->inverter_state |= unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->wheel_speed_sensor_state |= unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->signed_int_char |= unpack_right_shift_u8(src_p[2], 0u, 0xffu);

    return (0);
}

uint8_t enums_vehicle_status_inverter_state_encode(double value)
{
    return (uint8_t)(value);
}

double enums_vehicle_status_inverter_state_decode(uint8_t value)
{
    return ((double)value);
}

bool enums_vehicle_status_inverter_state_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t enums_vehicle_status_wheel_speed_sensor_state_encode(double value)
{
    return (uint8_t)(value);
}

double enums_vehicle_status_wheel_speed_sensor_state_decode(uint8_t value)
{
    return ((double)value);
}

bool enums_vehicle_status_wheel_speed_sensor_state_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t enums_vehicle_status_signed_int_char_encode(double value)
{
    return (uint8_t)(value);
}

double enums_vehicle_status_signed_int_char_decode(uint8_t value)
{
    return ((double)value);
}

bool enums_vehicle_status_signed_int_char_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}
