/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 29.7.0 Sun Dec  2 00:57:07 2018.
 */

#include <string.h>

#include "floating_point.h"

#define UNUSED(x) (void)(x)

static inline uint8_t encode_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t encode_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}


static inline uint8_t decode_left_shift_u8(
    uint8_t value,
    uint8_t mask,
    int shift)
{
    return (uint8_t)((uint8_t)(value & mask) << shift);
}


static inline uint8_t decode_right_shift_u8(
    uint8_t value,
    uint8_t mask,
    int shift)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint8_t encode_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t encode_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}


static inline uint16_t decode_left_shift_u16(
    uint8_t value,
    uint8_t mask,
    int shift)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}


static inline uint16_t decode_right_shift_u16(
    uint8_t value,
    uint8_t mask,
    int shift)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint8_t encode_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t encode_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}


static inline uint32_t decode_left_shift_u32(
    uint8_t value,
    uint8_t mask,
    int shift)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}


static inline uint32_t decode_right_shift_u32(
    uint8_t value,
    uint8_t mask,
    int shift)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

static inline uint8_t encode_left_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t encode_right_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}


static inline uint64_t decode_left_shift_u64(
    uint8_t value,
    uint8_t mask,
    int shift)
{
    return (uint64_t)((uint64_t)(value & mask) << shift);
}


static inline uint64_t decode_right_shift_u64(
    uint8_t value,
    uint8_t mask,
    int shift)
{
    return (uint64_t)((uint64_t)(value & mask) >> shift);
}

ssize_t floating_point_message1_encode(
    uint8_t *dst_p,
    const struct floating_point_message1_t *src_p,
    size_t size)
{
    uint64_t signal1;

    if (size < 8) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    memcpy(&signal1, &src_p->signal1, sizeof(signal1));
    dst_p[0] |= encode_left_shift_u64(signal1, 0, 0xffu);
    dst_p[1] |= encode_right_shift_u64(signal1, 8, 0xffu);
    dst_p[2] |= encode_right_shift_u64(signal1, 16, 0xffu);
    dst_p[3] |= encode_right_shift_u64(signal1, 24, 0xffu);
    dst_p[4] |= encode_right_shift_u64(signal1, 32, 0xffu);
    dst_p[5] |= encode_right_shift_u64(signal1, 40, 0xffu);
    dst_p[6] |= encode_right_shift_u64(signal1, 48, 0xffu);
    dst_p[7] |= encode_right_shift_u64(signal1, 56, 0xffu);

    return (8);
}

int floating_point_message1_decode(
    struct floating_point_message1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint64_t signal1;

    if (size < 8) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    signal1 = 0ull;
    signal1 |= decode_right_shift_u64(src_p[0], 255, 0x00u);
    signal1 |= decode_left_shift_u64(src_p[1], 255, 0x08u);
    signal1 |= decode_left_shift_u64(src_p[2], 255, 0x10u);
    signal1 |= decode_left_shift_u64(src_p[3], 255, 0x18u);
    signal1 |= decode_left_shift_u64(src_p[4], 255, 0x20u);
    signal1 |= decode_left_shift_u64(src_p[5], 255, 0x28u);
    signal1 |= decode_left_shift_u64(src_p[6], 255, 0x30u);
    signal1 |= decode_left_shift_u64(src_p[7], 255, 0x38u);
    memcpy(&dst_p->signal1, &signal1, sizeof(dst_p->signal1));

    return (0);
}

bool floating_point_message1_signal1_is_in_range(double value)
{
    UNUSED(value);

    return (true);
}

ssize_t floating_point_message2_encode(
    uint8_t *dst_p,
    const struct floating_point_message2_t *src_p,
    size_t size)
{
    uint32_t signal1;
    uint32_t signal2;

    if (size < 8) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    memcpy(&signal1, &src_p->signal1, sizeof(signal1));
    dst_p[0] |= encode_left_shift_u32(signal1, 0, 0xffu);
    dst_p[1] |= encode_right_shift_u32(signal1, 8, 0xffu);
    dst_p[2] |= encode_right_shift_u32(signal1, 16, 0xffu);
    dst_p[3] |= encode_right_shift_u32(signal1, 24, 0xffu);
    memcpy(&signal2, &src_p->signal2, sizeof(signal2));
    dst_p[4] |= encode_left_shift_u32(signal2, 0, 0xffu);
    dst_p[5] |= encode_right_shift_u32(signal2, 8, 0xffu);
    dst_p[6] |= encode_right_shift_u32(signal2, 16, 0xffu);
    dst_p[7] |= encode_right_shift_u32(signal2, 24, 0xffu);

    return (8);
}

int floating_point_message2_decode(
    struct floating_point_message2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t signal1;
    uint32_t signal2;

    if (size < 8) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    signal1 = 0u;
    signal1 |= decode_right_shift_u32(src_p[0], 255, 0x00u);
    signal1 |= decode_left_shift_u32(src_p[1], 255, 0x08u);
    signal1 |= decode_left_shift_u32(src_p[2], 255, 0x10u);
    signal1 |= decode_left_shift_u32(src_p[3], 255, 0x18u);
    memcpy(&dst_p->signal1, &signal1, sizeof(dst_p->signal1));
    signal2 = 0u;
    signal2 |= decode_right_shift_u32(src_p[4], 255, 0x00u);
    signal2 |= decode_left_shift_u32(src_p[5], 255, 0x08u);
    signal2 |= decode_left_shift_u32(src_p[6], 255, 0x10u);
    signal2 |= decode_left_shift_u32(src_p[7], 255, 0x18u);
    memcpy(&dst_p->signal2, &signal2, sizeof(dst_p->signal2));

    return (0);
}

bool floating_point_message2_signal1_is_in_range(float value)
{
    UNUSED(value);

    return (true);
}

bool floating_point_message2_signal2_is_in_range(float value)
{
    UNUSED(value);

    return (true);
}
