/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 37.0.3 Thu Jan 27 16:26:48 2022.
 */

#ifndef SHARED_SIGNAL_MUX_6_0_H
#define SHARED_SIGNAL_MUX_6_0_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define SHARED_SIGNAL_MUX_6_0_MUXED_SYMBOL_FRAME_ID (0x234u)

/* Frame lengths in bytes. */
#define SHARED_SIGNAL_MUX_6_0_MUXED_SYMBOL_LENGTH (8u)

/* Extended or standard frame types. */
#define SHARED_SIGNAL_MUX_6_0_MUXED_SYMBOL_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */


/**
 * Signals in message MuxedSymbol.
 *
 * All signal values are as on the CAN bus.
 */
struct shared_signal_mux_6_0_muxed_symbol_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t first_mux;

    /**
     * Range: ..1 (..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t shared_signal;

    /**
     * Range: ..1 (..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t shared_signal;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    int8_t first_signal_unique;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    int8_t second_signal_unique;
};

/**
 * Pack message MuxedSymbol.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int shared_signal_mux_6_0_muxed_symbol_pack(
    uint8_t *dst_p,
    const struct shared_signal_mux_6_0_muxed_symbol_t *src_p,
    size_t size);

/**
 * Unpack message MuxedSymbol.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int shared_signal_mux_6_0_muxed_symbol_unpack(
    struct shared_signal_mux_6_0_muxed_symbol_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t shared_signal_mux_6_0_muxed_symbol_first_mux_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double shared_signal_mux_6_0_muxed_symbol_first_mux_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool shared_signal_mux_6_0_muxed_symbol_first_mux_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t shared_signal_mux_6_0_muxed_symbol_shared_signal_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double shared_signal_mux_6_0_muxed_symbol_shared_signal_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool shared_signal_mux_6_0_muxed_symbol_shared_signal_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int8_t shared_signal_mux_6_0_muxed_symbol_first_signal_unique_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double shared_signal_mux_6_0_muxed_symbol_first_signal_unique_decode(int8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool shared_signal_mux_6_0_muxed_symbol_first_signal_unique_is_in_range(int8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int8_t shared_signal_mux_6_0_muxed_symbol_second_signal_unique_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double shared_signal_mux_6_0_muxed_symbol_second_signal_unique_decode(int8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool shared_signal_mux_6_0_muxed_symbol_second_signal_unique_is_in_range(int8_t value);


#ifdef __cplusplus
}
#endif

#endif
