/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 37.0.3 Thu Jan 27 19:37:06 2022.
 */

#include <string.h>

#include "shared_signal_mux_6_0.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

int shared_signal_mux_6_0_muxed_symbol_pack(
    uint8_t *dst_p,
    const struct shared_signal_mux_6_0_muxed_symbol_t *src_p,
    size_t size)
{
    uint8_t first_signal_unique;
    uint8_t second_signal_unique;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->first_mux, 0u, 0x01u);

    switch (src_p->first_mux) {

    case 0:
        dst_p[1] |= pack_left_shift_u8(src_p->shared_signal, 0u, 0xffu);
        first_signal_unique = (uint8_t)src_p->first_signal_unique;
        dst_p[2] |= pack_left_shift_u8(first_signal_unique, 0u, 0xffu);
        break;

    case 1:
        dst_p[1] |= pack_left_shift_u8(src_p->shared_signal, 0u, 0xffu);
        second_signal_unique = (uint8_t)src_p->second_signal_unique;
        dst_p[2] |= pack_left_shift_u8(second_signal_unique, 0u, 0xffu);
        break;

    default:
        break;
    }

    return (8);
}

int shared_signal_mux_6_0_muxed_symbol_unpack(
    struct shared_signal_mux_6_0_muxed_symbol_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t first_signal_unique;
    uint8_t second_signal_unique;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->first_mux = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    switch (dst_p->first_mux) {

    case 0:
        dst_p->shared_signal = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
        first_signal_unique = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
        dst_p->first_signal_unique = (int8_t)first_signal_unique;
        break;

    case 1:
        dst_p->shared_signal = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
        second_signal_unique = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
        dst_p->second_signal_unique = (int8_t)second_signal_unique;
        break;

    default:
        break;
    }

    return (0);
}

uint8_t shared_signal_mux_6_0_muxed_symbol_first_mux_encode(double value)
{
    return (uint8_t)(value);
}

double shared_signal_mux_6_0_muxed_symbol_first_mux_decode(uint8_t value)
{
    return ((double)value);
}

bool shared_signal_mux_6_0_muxed_symbol_first_mux_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t shared_signal_mux_6_0_muxed_symbol_shared_signal_encode(double value)
{
    return (uint8_t)(value);
}

double shared_signal_mux_6_0_muxed_symbol_shared_signal_decode(uint8_t value)
{
    return ((double)value);
}

bool shared_signal_mux_6_0_muxed_symbol_shared_signal_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int8_t shared_signal_mux_6_0_muxed_symbol_first_signal_unique_encode(double value)
{
    return (int8_t)(value);
}

double shared_signal_mux_6_0_muxed_symbol_first_signal_unique_decode(int8_t value)
{
    return ((double)value);
}

bool shared_signal_mux_6_0_muxed_symbol_first_signal_unique_is_in_range(int8_t value)
{
    return (value <= 1u);
}

int8_t shared_signal_mux_6_0_muxed_symbol_second_signal_unique_encode(double value)
{
    return (int8_t)(value);
}

double shared_signal_mux_6_0_muxed_symbol_second_signal_unique_decode(int8_t value)
{
    return ((double)value);
}

bool shared_signal_mux_6_0_muxed_symbol_second_signal_unique_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}
