/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 28.8.1 Tue Oct 23 21:36:17 2018.
 */

#include <string.h>

#include "padding_bit_order.h"

#ifndef EINVAL
#    define EINVAL -22
#endif

ssize_t padding_bit_order_msg0_encode(
    uint8_t *dst_p,
    struct padding_bit_order_msg0_t *src_p,
    size_t size)
{
    if (size < 8) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= ((src_p->b << 7) & 0x80);
    dst_p[0] |= ((src_p->a >> 8) & 0x7f);
    dst_p[1] |= ((src_p->a << 0) & 0xff);
    dst_p[4] |= ((src_p->d << 7) & 0x80);
    dst_p[4] |= ((src_p->c >> 8) & 0x7f);
    dst_p[5] |= ((src_p->c << 0) & 0xff);

    return (8);
}

int padding_bit_order_msg0_decode(
    struct padding_bit_order_msg0_t *dst_p,
    uint8_t *src_p,
    size_t size)
{
    return (0);
}

ssize_t padding_bit_order_msg1_encode(
    uint8_t *dst_p,
    struct padding_bit_order_msg1_t *src_p,
    size_t size)
{
    if (size < 8) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= ((src_p->e << 0) & 0x01);
    dst_p[0] |= ((src_p->f << 1) & 0xfe);
    dst_p[1] |= ((src_p->f >> 7) & 0xff);
    dst_p[4] |= ((src_p->g << 0) & 0x01);
    dst_p[4] |= ((src_p->h << 1) & 0xfe);
    dst_p[5] |= ((src_p->h >> 7) & 0xff);

    return (8);
}

int padding_bit_order_msg1_decode(
    struct padding_bit_order_msg1_t *dst_p,
    uint8_t *src_p,
    size_t size)
{
    return (0);
}

ssize_t padding_bit_order_msg2_encode(
    uint8_t *dst_p,
    struct padding_bit_order_msg2_t *src_p,
    size_t size)
{
    if (size < 8) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= ((src_p->i << 0) & 0x0f);
    dst_p[0] |= ((src_p->j << 4) & 0xf0);
    dst_p[1] |= ((src_p->k << 0) & 0x0f);

    return (8);
}

int padding_bit_order_msg2_decode(
    struct padding_bit_order_msg2_t *dst_p,
    uint8_t *src_p,
    size_t size)
{
    return (0);
}

ssize_t padding_bit_order_msg3_encode(
    uint8_t *dst_p,
    struct padding_bit_order_msg3_t *src_p,
    size_t size)
{
    if (size < 8) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= ((src_p->l >> 56) & 0xff);
    dst_p[1] |= ((src_p->l >> 48) & 0xff);
    dst_p[2] |= ((src_p->l >> 40) & 0xff);
    dst_p[3] |= ((src_p->l >> 32) & 0xff);
    dst_p[4] |= ((src_p->l >> 24) & 0xff);
    dst_p[5] |= ((src_p->l >> 16) & 0xff);
    dst_p[6] |= ((src_p->l >> 8) & 0xff);
    dst_p[7] |= ((src_p->l << 0) & 0xff);

    return (8);
}

int padding_bit_order_msg3_decode(
    struct padding_bit_order_msg3_t *dst_p,
    uint8_t *src_p,
    size_t size)
{
    return (0);
}

ssize_t padding_bit_order_msg4_encode(
    uint8_t *dst_p,
    struct padding_bit_order_msg4_t *src_p,
    size_t size)
{
    if (size < 8) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= ((src_p->m << 0) & 0xff);
    dst_p[1] |= ((src_p->m >> 8) & 0xff);
    dst_p[2] |= ((src_p->m >> 16) & 0xff);
    dst_p[3] |= ((src_p->m >> 24) & 0xff);
    dst_p[4] |= ((src_p->m >> 32) & 0xff);
    dst_p[5] |= ((src_p->m >> 40) & 0xff);
    dst_p[6] |= ((src_p->m >> 48) & 0xff);
    dst_p[7] |= ((src_p->m >> 56) & 0xff);

    return (8);
}

int padding_bit_order_msg4_decode(
    struct padding_bit_order_msg4_t *dst_p,
    uint8_t *src_p,
    size_t size)
{
    return (0);
}
